### ISSUE TITLE
DCO-bot doesn’t accept my Signature.

### ISSUE THREAD

**Issue by vonneudeck** [scottrigby/dco-gh-ui#7]
The DCO bot doesn’t accept the Signature generated by the Addon.
If I sign using git on the command line, this is the result and it is accepted:

`    Signed-off-by: Nicolai von Neudeck <nicolai@vonneudeck.com>` 

If I fill out the forms in the preferences of your addon with `Nicolai von Neudeck` and `nicolai@vonneudeck.com` the resulting

`Signed-off-by: Nicolai von Neudeck <nicolai@vonneudeck.com>`

is not accepted by the DCO-bot. 
Both look the same to me.

**Comment by mattfarina** [comment]
@vonneudeck which DCO bot?

**Comment by vonneudeck** [comment]
This one https://probot.github.io/apps/dco/

**Comment by scottrigby** [comment]
@vonneudeck If the same string is correctly added to a commit it should work for DCO. It doesn't sound like an issue with this add-on, but can you point to an example commit in a public repo so we can see what the issue might be?

**Comment by vonneudeck** [comment]
Sorry for not answering so long, life was weird in the pandemic.
The problem happened again recently here:
https://github.com/cortexproject/cortex/pull/4009/checks?check_run_id=2194259050
So if you are still interested, I opened an issue at probot:
https://github.com/probot/dco/issues/151

**Comment by vonneudeck** [comment]
It is pretty mysterious to me, maybe you have an idea what it could be?

**Comment by scottrigby** [comment]
That is interesting. I'm going to close this as it appears to be via probot and unrelated to this browser plugin. Good luck tracking that one down 💖 🤞
